const data = {
    canvas: document.querySelector("#create-character_view-character"),
    canvasFight: document.querySelector("#fight-view"),
    isGamePlay: true,
    arr: [0, 0.5, 1, 1.5, 2, 2.5, 2.5, 2, 1.5, 1, 0.5, 0],
    pos: 0,
    characterHealth: 1000,
    monsterHealth: 1000,
    animationCount: 0,
    isAnimate: false,
    spellCount: 0,
    answer: 0,
    mathSigns: ["+", "-", "*", "/"],
    worldsList: [
        {world: "yellow",
         translate: ["оранжевый", "желтый", "синий", "розовый"],
         trueTranslate: 1},
        {world: "grey",
         translate: ["белый", "розовый", "серый", "оранжевый"],
         trueTranslate: 2},
        {world: "blue",
         translate: ["синий", "оранжевый", "красный", "серый"],
         trueTranslate: 0},
        {world: "white",
         translate: ["розовый", "синий", "зеленый", "белый"],
         trueTranslate: 3},
        {world: "orange",
         translate: ["оранжевый", "серый", "красный", "зеленый"],
         trueTranslate: 0}],
    monsterName: [["Hungry", "Evil", "Harmful", "Sad", "Alone"],["Dragon", "Monster", "Bird"]],
    nowStep: "character",
    imageList: ["sources/images/heroes-part/body-cat.png",
        "sources/images/heroes-part/body-dog.png",
        "sources/images/heroes-part/body-panda.png",
        "sources/images/heroes-part/hand1-cat.png",
        "sources/images/heroes-part/hand1-dog.png",
        "sources/images/heroes-part/hand1-panda.png",
        "sources/images/heroes-part/head-cat.png",
        "sources/images/heroes-part/head-dog.png",
        "sources/images/heroes-part/head-panda.png",
        "sources/images/heroes-part/hand2-cat.png",
        "sources/images/heroes-part/hand2-dog.png",
        "sources/images/heroes-part/hand2-panda.png",
        "sources/images/heroes-part/leg1-cat.png",
        "sources/images/heroes-part/leg1-dog.png",
        "sources/images/heroes-part/leg1-panda.png",
        "sources/images/heroes-part/leg2-cat.png",
        "sources/images/heroes-part/leg2-dog.png",
        "sources/images/heroes-part/leg2-panda.png",
        "sources/images/heroes-sprite.png",
        "sources/images/monster-sprite.png",
        "sources/images/pentagon.png",
        "sources/images/spells-sprite.png",
        "sources/images/game-bg.png",
        "sources/images/spell/fire-ball.png",
        "sources/images/spell/lighting.png",
        "sources/images/spell/shuriken.png",
        "sources/images/spell/energy-rain.png"],
    monster: [
        [0, 932, [77, 81], 'leg2', 66/2, 395/2, "sources/images/monster-sprite.png"],
        [0, 787, [89, 145], 'hand2', 18/2, 226/2, "sources/images/monster-sprite.png"],
        [0, 568, [305, 219], 'body', 58/2, 205/2, "sources/images/monster-sprite.png"],
        [0, 432, [100, 136], 'leg1', 130/2, 370/2, "sources/images/monster-sprite.png"],
        [0, 242, [101, 190], 'hand1', 192/2, 227/2, "sources/images/monster-sprite.png"],
        [0, 0, [291, 242], 'head', 0, 0, "sources/images/monster-sprite.png"]
    ],
    fireBallPos: [0,0],
    fireBallCount: 0,
    fireBallCadr: 0,
    lightningCount: 0,
    lightningCadr: 0,
    shurikenCount: 0,
    shurikenCadr: 0,
    shurikenPos: 0,
    energyRainCount: 0,
    energyRainCadr: 0,
    energyRainPos: [0, 0]
};
